version: '3'
services:
  db:
    build: "db/."
    env_file:
      - .env
    restart: on-failure
    volumes:
      - database:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  database: